"""empty message

Revision ID: 60480e1b6d62
Revises: 
Create Date: 2021-11-19 22:10:54.769429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60480e1b6d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beans', sa.String(length=12), nullable=False),
    sa.Column('milk', sa.Integer(), nullable=False),
    sa.Column('sugar', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furniture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('on_surface', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('console', sa.String(length=12), nullable=False),
    sa.Column('year_released', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('personalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('gender', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('villagers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('species', sa.String(length=12), nullable=False),
    sa.Column('birthday_month', sa.Integer(), nullable=False),
    sa.Column('birthday_day', sa.Integer(), nullable=False),
    sa.Column('catchphrase', sa.String(length=12), nullable=True),
    sa.Column('hobby', sa.String(length=12), nullable=True),
    sa.Column('fav_color', sa.String(length=12), nullable=True),
    sa.Column('fav_song', sa.String(length=12), nullable=True),
    sa.Column('is_sanrio', sa.Boolean(), nullable=True),
    sa.Column('subtype', sa.String(length=1), nullable=True),
    sa.Column('personality_id', sa.Integer(), nullable=False),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('amiibos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series', sa.String(length=20), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('villager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['villager_id'], ['villagers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallpaper', sa.String(length=12), nullable=False),
    sa.Column('floor', sa.String(length=12), nullable=False),
    sa.Column('music', sa.String(length=12), nullable=True),
    sa.Column('villager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['villager_id'], ['villagers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('villagers_games',
    sa.Column('villager_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['villager_id'], ['villagers.id'], ),
    sa.PrimaryKeyConstraint('villager_id', 'game_id')
    )
    op.create_table('houses_furniture',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('furniture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['furniture_id'], ['furniture.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('house_id', 'furniture_id')
    )
    op.create_table('houses_games',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('house_id', 'game_id')
    )
    op.create_table('nfc_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('written', sa.Boolean(), nullable=False),
    sa.Column('drawn', sa.Boolean(), nullable=False),
    sa.Column('amiibo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amiibo_id'], ['amiibos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfc_tags')
    op.drop_table('houses_games')
    op.drop_table('houses_furniture')
    op.drop_table('villagers_games')
    op.drop_table('houses')
    op.drop_table('amiibos')
    op.drop_table('villagers')
    op.drop_table('personalities')
    op.drop_table('games')
    op.drop_table('furniture')
    op.drop_table('coffees')
    # ### end Alembic commands ###
